{
 "title": "ZFS stats",
 "description": "Graphs ZFS ARC and ARC L2 Hit %, Hits, Misses, Size, and Zpool",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_exporter_build_info, instance)"
   },
   {
    "name": "port",
    "query": "label_values(node_exporter_build_info{instance=~\"$node:(.*)\"}, instance)"
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ZPOOL State",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "node_zfs_zpool_state == 1", "legendFormat": "{{zpool}} {{state}}" }
   ]
  },
  { "title": "Datasets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Dataset - Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(node_zfs_zpool_dataset_nread[5m])",
     "legendFormat": "nread - {{dataset}}"
    },
    {
     "expr": "irate(node_zfs_zpool_dataset_nwritten[5m])",
     "legendFormat": "nwritten - {{dataset}}"
    }
   ]
  },
  {
   "title": "Dataset - Ops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_zfs_zpool_dataset_reads[5m])",
     "legendFormat": "reads - {{dataset}}"
    },
    {
     "expr": "irate(node_zfs_zpool_dataset_writes[5m])",
     "legendFormat": "writes - {{dataset}}"
    }
   ]
  },
  { "title": "ARC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "ARC - Hit %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(node_zfs_arc_demand_data_hits[5m]) / (irate(node_zfs_arc_demand_data_hits[5m]) + irate(node_zfs_arc_demand_data_misses[5m])) * 100",
     "legendFormat": "data"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_hits[5m]) / (irate(node_zfs_arc_demand_metadata_hits[5m]) + irate(node_zfs_arc_demand_metadata_misses[5m])) * 100",
     "legendFormat": "metadata"
    }
   ]
  },
  {
   "title": "ARC - Hits, Misses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_zfs_arc_demand_data_hits[5m])",
     "legendFormat": "data_hits"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_hits[5m])",
     "legendFormat": "metadata_hits"
    },
    {
     "expr": "irate(node_zfs_arc_demand_data_misses[5m])",
     "legendFormat": "data_misses"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_misses[5m])",
     "legendFormat": "metadata_misses"
    }
   ]
  },
  {
   "title": "ARC - Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_zfs_arc_data_size", "legendFormat": "data" },
    { "expr": "node_zfs_arc_metadata_size", "legendFormat": "metadata" },
    { "expr": "node_zfs_arc_anon_size", "legendFormat": "anon" },
    { "expr": "node_zfs_arc_hdr_size", "legendFormat": "hdr" },
    { "expr": "node_zfs_arc_other_size", "legendFormat": "other" }
   ]
  },
  { "title": "ARC L2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "ARC L2 - Hit %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(node_zfs_arc_l2_hits[5m]) / (irate(node_zfs_arc_l2_hits[5m]) + irate(node_zfs_arc_l2_misses[5m])) * 100",
     "legendFormat": "L2"
    }
   ]
  },
  {
   "title": "ARC L2 - Hits, Misses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_zfs_arc_l2_hits[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(node_zfs_arc_l2_misses[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "ARC L2 - Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_zfs_arc_l2_asize", "legendFormat": "asize" },
    { "expr": "node_zfs_arc_l2_hdr_size", "legendFormat": "metadata" },
    { "expr": "node_zfs_arc_l2_size", "legendFormat": "size" }
   ]
  }
 ]
}